---
# tasks file for postgresql
- name: install PostgreSQL 9.4
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql94
    - postgresql94-server
    - postgresql94-devel
    - postgresql94-contrib
    - postgresql94-docs
    - python27-psycopg2
  tags: install-psql

- name: initialize database
  shell: /etc/init.d/postgresql94 initdb
  ignore_errors: True
  tags: initdb

- name: set postgresql94 service state
  service:
    name: postgresql94
    enabled: yes
    state: started
  tags: set-service-state

- name: change postgresql config
  block:
    - lineinfile: path=/var/lib/pgsql94/data/postgresql.conf state=present insertafter='^#listen_addresses =' line="listen_addresses = '*'" owner=postgres group=postgres mode=0600 backup=yes
      # notify: restart postgresql94
    - copy: src=files/var/lib/pgsql94/data/pg_hba.conf dest=/var/lib/pgsql94/data/pg_hba.conf owner=postgres group=postgres mode=0600 backup=yes
      # notify: restart postgresql94
  tags: change-psql-config

- name: restart postgresql94
  service:
    name: postgresql94
    state: restarted
  tags: restart-psql

- name: create roles
  postgresql_user:
    name: "{{ psql_role }}"
    role_attr_flags: SUPERUSER,LOGIN
  # notify: restart postgresql94
  tags: create-roles

- name: create databases
  postgresql_db:
    name: "{{ psql_db }}"
  # notify: restart postgresql94
