---
- name: install nginx
  yum:
    name: nginx
    state: latest
  tags: install-nginx
  when: "'install-nginx' in tasks"

- name: set nginx service state
  service:
    name: nginx
    enabled: yes
    state: started
  tags: set-service-state
  when: "'set-service-state' in tasks"

- name: add rails app config
  template:
    src: templates/etc/nginx/conf.d/rails_app.conf.j2
    dest: /etc/nginx/conf.d/{{ rails_app }}.conf
    backup: yes
  notify: restart nginx
  tags: add-rails-app-config
  when: "'add-rails-app-config' in tasks"
